
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LAB-RPL2-PC02
 */
public class ukk_zaky extends javax.swing.JFrame {
    Connection koneksi;
    String id_obat = "";
    /**
     * Creates new form ukk_zaky
     */
    public ukk_zaky() {
        initComponents();
        koneksi();
        tampil ();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_simpan = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_utama = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_id_tx = new javax.swing.JTextField();
        txt_namaobat = new javax.swing.JTextField();
        txt_val = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jLabel1.setText("UNIT KESEHATAN SEKOLAH");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 220, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("SMKN 1 SAYUNG");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\LAB-RPL2-PC02\\Downloads\\logo1.png")); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabel3.setMinimumSize(new java.awt.Dimension(100, 100));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 170));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("SEKOLAH SEHAT SISWA KUAT !");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        jLabel5.setText("PILIH AKSI :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 80, -1));

        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        getContentPane().add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 80, -1));

        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        getContentPane().add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 80, -1));

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        getContentPane().add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 80, -1));

        tb_utama.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID obat", "ID transaksi", "Nama Obat", "Validasi"
            }
        ));
        jScrollPane1.setViewportView(tb_utama);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 250, 560, 110));

        jLabel7.setText("ID TRANSAKSI :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, -1));

        jLabel8.setText("NAMA OBAT  :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));

        jLabel9.setText("VALIDASI         :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));
        getContentPane().add(txt_id_tx, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 180, -1));
        getContentPane().add(txt_namaobat, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 180, -1));
        getContentPane().add(txt_val, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 180, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        if(id_obat == "") {
            tambah();
        }else {
            update();
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        hapus();
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        edit();
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btn_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ukk_zaky.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ukk_zaky.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ukk_zaky.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ukk_zaky.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ukk_zaky().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_utama;
    private javax.swing.JTextField txt_id_tx;
    private javax.swing.JTextField txt_namaobat;
    private javax.swing.JTextField txt_val;
    // End of variables declaration//GEN-END:variables

 private void  koneksi(){
    try {
        String server = "jdbc:mysql://localhost:3306/db_ukk_lsp_zaky";
        String user = "root";
        String pass = "";

        DriverManager.registerDriver(new com.mysql.cj.jdbc.Driver());
        koneksi = DriverManager.getConnection(server, user, pass);
   } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
}
 
 private void tampil(){
     DefaultTableModel data = (DefaultTableModel) tb_utama.getModel();
    data.setRowCount(0);

    try {
        String sql = "SELECT * FROM tb_utama";
        ResultSet res = koneksi.createStatement().executeQuery(sql);
        while(res.next()){
                data.addRow(new Object[]{
                    res.getString(1),res.getString(2),
                    res.getString(3), res.getString(4)});
                    tb_utama.setModel(data);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
}
 
 private void tambah(){
    try {
        String sql = "INSERT INTO tb_utama VALUES (null," 
                + "'" + txt_id_tx.getText()+ "',"
                + "'" + txt_namaobat.getText() + "',"
                + "'" + txt_val.getText() + "')";

        int res = koneksi.createStatement().executeUpdate(sql);

        if (res > -1) {
            tampil();
            txt_id_tx.setText("");
            txt_namaobat.setText("");
            txt_val.setText("");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
}

 private void hapus(){
     int row = tb_utama.getSelectedRow();
    String id_bt = tb_utama.getValueAt(row, 0).toString();

    try {
        String sql = "DELETE FROM tb_utama WHERE id_obat="+id_bt;
        int res = koneksi.createStatement().executeUpdate(sql);

        if (res > -1) {
            tampil();

        }
    } catch (Exception e) {
    }

}

 private void edit(){
    int row = tb_utama.getSelectedRow();
    String id_obatt = tb_utama.getValueAt(row, 0).toString();

    try {
        String sql = "SELECT * FROM tb_utama WHERE id_obat="+id_obatt;
        ResultSet res = koneksi.createStatement().executeQuery(sql);

        while (res.next()) {
            id_obat = res.getString(1);
            txt_id_tx.setText(res.getString(2));
            txt_namaobat.setText(res.getString(3));
            txt_val.setText(res.getString(4));
            btn_edit.setEnabled(false);

        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
}
 
 private void clear(){
            id_obat = null;
            txt_id_tx.setText("");
            txt_namaobat.setText("");
            txt_val.setText("");
            btn_edit.setEnabled(true);
}
 
 private void update(){
    try {
        String sql = "UPDATE tb_utama SET "
                + "id_transaksi = '" + txt_id_tx.getText() + "',"
                + "nama_obat = '" + txt_namaobat.getText()+ "',"
                + "validasi = '" + txt_val.getText() + "'  "
                + "WHERE id_obat = " + id_obat;

        int res = koneksi.createStatement().executeUpdate(sql);

        if (res > -1) {
            tampil();
            clear();
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
}
}
